### ISSUE TITLE
Unable to run tests using on browserstack

### ISSUE THREAD

**Issue by agubler** [dojo/cli-test-intern#77]
**Bug**

Running `dojo test -a -c "browserstack"` fails, whilst using the local tunnel or saucelabs run successfully.

```
building "dojo2-todo-mvc"...
ts-loader: Using typescript@2.4.2 and /Users/Anthony/development/dojo2/examples/todo-mvc/tsconfig.json
Hash: bd396845ae9b73eed140
Version: webpack 2.7.0
Time: 12024ms
                                Asset       Size  Chunks                    Chunk Names
             ../_build/src/src.js.map    53.5 kB       3  [emitted]         src
                ../_build/src/main.js     348 kB       0  [emitted]  [big]  ../_build/src/main
    ../_build/tests/functional/all.js    89.1 kB       2  [emitted]         ../_build/tests/functional/all
                 ../_build/src/src.js     164 kB       3  [emitted]         src
                             main.css    6.71 kB    0, 2  [emitted]         ../_build/src/main, ../_build/tests/functional/all
            ../_build/src/main.js.map     545 kB       0  [emitted]         ../_build/src/main
                         main.css.map     9.7 kB    0, 2  [emitted]         ../_build/src/main, ../_build/tests/functional/all
      ../_build/tests/unit/all.js.map  914 bytes       1  [emitted]         ../_build/tests/unit/all
../_build/tests/functional/all.js.map     116 kB       2  [emitted]         ../_build/tests/functional/all
          ../_build/tests/unit/all.js    1.03 kB       1  [emitted]         ../_build/tests/unit/all
                           index.html  114 bytes          [emitted]
           widgets/styles/todoApp.css  247 bytes          [emitted]
        widgets/styles/todoFilter.css  411 bytes          [emitted]
        widgets/styles/todoFooter.css  714 bytes          [emitted]
        widgets/styles/todoHeader.css    1.13 kB          [emitted]
                              main.js    3.12 kB          [emitted]
          widgets/styles/todoItem.css    2.12 kB          [emitted]
          widgets/styles/todoList.css  167 bytes          [emitted]
             ../_build/src/index.html  321 bytes          [emitted]
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks  Chunk Names
    index.html  3.02 kB       0
Child html-webpack-plugin for "../_build/src/index.html":
                       Asset     Size  Chunks  Chunk Names
    ../_build/src/index.html  3.02 kB       0

testing "dojo2-todo-mvc"...

Listening on localhost:9000 (ws 9001)
Tunnel started
BUG: suiteEnd was received for invalid session
(ノಠ益ಠ)ノ彡┻━┻
Error: [POST https://(redacted)@localhost:4444/wd/hub/session] connect ECONNREFUSED 127.0.0.1:4444
  at Server.post  <node_modules/src/Server.ts:367:14>
  at Server.createSession  <node_modules/src/Server.ts:412:14>
  at Suite.before  <src/lib/executors/Node.ts:475:8>
  at <src/lib/Suite.ts:387:19>
  at new Task  <node_modules/intern/node_modules/@dojo/core/async/Task.ts:210:3>
  at runLifecycleMethod  <src/lib/Suite.ts:354:10>
  at before  <src/lib/Suite.ts:457:10>
  at Suite.run  <src/lib/Suite.ts:476:6>
  at <src/lib/executors/Node.ts:929:20>
  at FunctionQueue.next  <src/lib/executors/Node.ts:1308:13>

TOTAL: tested 0 platforms, 0 passed, 0 failed; fatal error occurred
BUG: suiteEnd was received for invalid session
BUG: suiteEnd was received for invalid session
Stopped
  testing failed
```

To reproduce create a fresh Dojo 2 project using `dojo create`, export browserstack credentials and run `dojo test -a -c "browserstack"`

**Comment by agubler** [comment]
Just tested this with the latest master including #100 and it worked for both browserstack and saucelans
